### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Duplicake-fyi** [filippz/telegram_import#14]
I backed up my chat with someone else (by clicking on the export chat button) but they deleted their account. I am trying to import the backup into telegram, but I get this error:

usage: telegram_import [-h] --path PATH --peer PEER [--test_only]
telegram_import: error: argument --peer: expected one argument
zsh: command not found: NUMBER OF PERSON I'M CHATTING TO

My command is like this: python3 telegram_import.py --path "/Users/MY USER/Downloads/JsonMessages" --peer
"+44{rest of number, no spaces. Also, the number of the person I'm chatting to}"

I'm on a Mac and the API key I inputted into the config is an API key made on my account (and phone number of course) from https://my.telegram.org/apps

I don't know if this is a bug or me just not understanding the syntax.

**Comment by filippz** [comment]
Looks like the code is having trouble parsing the command line - my guess is that you simply have placed the peer number `"+44..."` on a separate line so Mac considers it like two commands and throws two errors (one from `telegram_import` about missing peer value, and the second one about it not being able to find the command `"+44..."`) Please not that the error `--peer PEER` suggest that `PEER` should be following `--peer` after a space.

**Comment by Duplicake-fyi** [comment]
I'll try it on linux

**Comment by Duplicake-fyi** [comment]
Whenever I run it on linux, I get this issue:

Loading config.ini
Loading result.json
Traceback (most recent call last):
  File "/home/myuser/Downloads/Telegram import/telegram_import.py", line 256, in <module>
    import_history(
    ~~~~~~~~~~~~~~^
        path=args.path,
        ^^^^^^^^^^^^^^^
        peer=args.peer,
        ^^^^^^^^^^^^^^^
        test_only=args.test_only
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/myuser/Downloads/Telegram import/telegram_import.py", line 186, in import_history
    with open(file, encoding='utf-8') as f:
         ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/myuser/Downloads/chatfolder\\result.json'


I don't know what's the issue, because I checked the path with my file manager. It definitely exists, something is wrong with the script.

**Comment by filippz** [comment]
I have (hopefully) fixed path/filename handling on non Windows systems (https://github.com/filippz/telegram_import/commit/56827c08227c8325451c006df1602edb7dda3830). Please try with those changes and let me know if you still have issues.
